# Generated by Django 4.2.4 on 2023-08-25 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=128, verbose_name='昵称')),
                ('realname', models.CharField(max_length=128, verbose_name='中文名字')),
                ('gender', models.IntegerField(choices=[(0, '未知直升机'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
