# Generated by Django 4.2.4 on 2023-09-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profile', models.ImageField(default='TeamProfile/default.png', upload_to='TeamProfile/')),
                ('isReal', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApi.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UnreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApi.userinfo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamApi.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'file')])),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Images/')),
                ('file', models.FileField(null=True, upload_to='Files/')),
                ('fileName', models.CharField(max_length=128, null=True)),
                ('isGroup', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='UserApi.userinfo')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='UserApi.userinfo')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamApi.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, '创建者'), (1, '管理员'), (2, '普通用户')], default=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApi.userinfo')),
                ('teamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamApi.team')),
            ],
        ),
        migrations.CreateModel(
            name='SingleUnread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='UserApi.userinfo')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='UserApi.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SingleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'file')])),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Images/')),
                ('file', models.FileField(null=True, upload_to='Files/')),
                ('fileName', models.CharField(max_length=128, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receiveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_msg', to='UserApi.userinfo')),
                ('sendUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_msg', to='UserApi.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AtMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApi.userinfo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamApi.team')),
                ('teamMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamApi.teammessage')),
            ],
        ),
    ]
