# Generated by Django 4.2.4 on 2023-09-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleunread',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
