# Generated by Django 4.2.4 on 2023-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreadmessage',
            name='teamMessage',
        ),
        migrations.AddField(
            model_name='unreadmessage',
            name='nums',
            field=models.IntegerField(default=1),
        ),
    ]
