# Generated by Django 4.2.4 on 2023-08-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammessage',
            name='file',
            field=models.FileField(null=True, upload_to='Files/'),
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
