# Generated by Django 4.2.4 on 2023-08-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0001_initial'),
        ('TeamApi', '0002_remove_unreadmessage_teammessage_unreadmessage_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleUnread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=1)),
                ('receiveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_un', to='UserApi.userinfo')),
                ('sendUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_un', to='UserApi.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SingleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'file')])),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Images/')),
                ('file', models.FileField(null=True, upload_to='Files/')),
                ('fileName', models.CharField(max_length=128, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receiveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_msg', to='UserApi.userinfo')),
                ('sendUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_msg', to='UserApi.userinfo')),
            ],
        ),
    ]
