# Generated by Django 4.2.4 on 2023-08-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApi', '0003_singleunread_singlemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleUnread',
        ),
    ]
