# Generated by Django 4.2.4 on 2023-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApi', '0005_singleunread'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='isReal',
            field=models.BooleanField(default=True),
        ),
    ]
