# Generated by Django 4.2.4 on 2023-08-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TeamApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName', models.CharField(max_length=128)),
                ('context', models.TextField(null=True)),
                ('lastEditTime', models.DateTimeField(auto_now_add=True)),
                ('lastEditPerson', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=128)),
                ('isDelete', models.BooleanField(default=False)),
                ('image', models.ImageField(default='ProjectProfile/1.jpg', upload_to='ProjectProfile/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamApi.team')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('str', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('isWrite', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('validity', models.DateTimeField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApi.document')),
            ],
        ),
        migrations.CreateModel(
            name='PrototypePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prototypeName', models.CharField(max_length=128)),
                ('context', models.TextField(null=True)),
                ('lastEditTime', models.DateTimeField(auto_now_add=True)),
                ('lastEditPerson', models.EmailField(max_length=254, null=True)),
                ('onEdit', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApi.project')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApi.project'),
        ),
    ]
