# Generated by Django 4.2.4 on 2023-09-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docID', models.IntegerField()),
                ('context', models.TextField(null=True)),
                ('saveTime', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
    ]
