# Generated by Django 4.2.4 on 2023-08-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypepage',
            name='length',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='prototypepage',
            name='width',
            field=models.IntegerField(default=200),
        ),
    ]
