# Generated by Django 4.2.4 on 2023-08-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0002_prototypepage_length_prototypepage_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prototypepage',
            old_name='length',
            new_name='height',
        ),
    ]
