# Generated by Django 4.2.4 on 2023-08-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0003_rename_length_prototypepage_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='validity',
            field=models.DurationField(null=True),
        ),
    ]
