# Generated by Django 4.2.4 on 2023-08-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0004_alter_sharelink_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='createTime',
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='validity',
            field=models.DateTimeField(null=True),
        ),
    ]
