# Generated by Django 4.2.4 on 2023-08-27 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0001_initial'),
        ('ProjectApi', '0005_remove_sharelink_createtime_alter_sharelink_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApi.document')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApi.userinfo')),
            ],
        ),
    ]
