# Generated by Django 4.2.4 on 2023-08-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0006_docat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docat',
            name='cnt',
        ),
    ]
