# Generated by Django 4.2.4 on 2023-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0008_alter_prototypepage_onedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default='2023-8-30 11:27:27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='dict',
            field=models.JSONField(default=list),
        ),
    ]
